// Generated by scripts/optimize-images.mjs — do not edit by hand.
export const IMAGE_PLACEHOLDERS: Record<string, string> = {
  "color-gray": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQABAAA4BaJaQAAuX7jibww4AA/vUkwr84csVDoFBiLZqsLxXuTrlCo/YWS6Jw5pQ/UHp3EGvaUg/PucaadYknJG7AAA==",
  "color-black": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQABAAA4BaJaQAAucscAxu00AA/u3vdPoWUKL7E2lVlHUM7pjx5ITvxP2VTWgv88FOpmzJE2MK5ypHAROqqHTM5wGZoSMctbQAAA==",
  "color-blue": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQABAAA4BaJbACdAEQE+dyLN2CAAD+8j5cKwzXU08s6gFuyUl3MJcVl0pRVFQSshnc6SnoYKbw3pqXS/j0Ug2wAgb51dIZ9piK0eQzJUX38ODv667VC5OvRfOzhVwA",
  "color-red": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQABAAA4BaJbACdAEQCKR0r9QAAP7z0L1QH9PToiBGm0Vd0hnPJEPXx6qgLouViulq58O8PJtC8Plk/XKURRE26c2zZ+wovtHYm33fLPAPyJcP9R89GjGsh6LPa8H4AAA=",
  "step-place-over-load": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABsAPu1iqU2ppaOiMAgBMB2JaQAAW9aRgCc81AP/omYAAP7qeM50+FAfejJ+0duhaUYPe3Mi9sBKKdcmJIecwUQ4r13pG/JbPStAsowcaMdYAbrXUotgIQOpmq+WKAA=",
  "step-stretch-over-container": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoQABsAPu1Ct1apoqakGAEwHYlpAAEd6K3pjU/zMFuqHzwAAP74spyjnmf463/LIPMWX3pstXy1ZxW6tzGpDdPRINmqsllWc7gOb56HHumWvc2A5AAAAA==",
  "step-secure-under-rim": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoQABsAPu1yrU+pp6QiMAgBMB2JaQABHunqjPuuK0Fa1uQQAP75bj9sGGihv/znBmzj7Dn6nZ5cXp8uVrJkJnd57lvLMpfWFUYWUNAJcK8MsVJ3AAA="
};
