// Generates responsive AVIF/WebP variants and inline blur placeholders for the
// product-options and how-it-works images. Re-run after replacing a source PNG:
//   node scripts/optimize-images.mjs
import sharp from "sharp";
import { writeFile } from "node:fs/promises";

const DIR = "public/images/tiltshield";
const GROUPS = {
  // Rendered at ~176–192 CSS px square (up to ~3× on phones).
  color: { names: ["color-gray", "color-black", "color-blue", "color-red"], widths: [256, 384, 640] },
  // Rendered at ~350–400 CSS px wide in a 3:5 frame (up to ~3× on phones).
  step: {
    names: ["step-place-over-load", "step-stretch-over-container", "step-secure-under-rim"],
    widths: [480, 720, 971],
  },
};

const placeholders = {};
for (const { names, widths } of Object.values(GROUPS)) {
  for (const name of names) {
    const src = sharp(`${DIR}/${name}.png`);
    const { width } = await src.metadata();
    for (const w of widths.filter((w) => w <= width)) {
      const resized = src.clone().resize({ width: w });
      await resized.clone().avif({ quality: 55, effort: 6 }).toFile(`${DIR}/${name}-${w}.avif`);
      await resized.clone().webp({ quality: 78, effort: 6 }).toFile(`${DIR}/${name}-${w}.webp`);
    }
    const tiny = await src.clone().resize({ width: 16 }).blur(0.6).webp({ quality: 40 }).toBuffer();
    placeholders[name] = `data:image/webp;base64,${tiny.toString("base64")}`;
  }
}

await writeFile(
  "src/lib/image-placeholders.ts",
  `// Generated by scripts/optimize-images.mjs — do not edit by hand.\nexport const IMAGE_PLACEHOLDERS: Record<string, string> = ${JSON.stringify(placeholders, null, 2)};\n`,
);
console.log("done");
